name: Test

on:
  push:
    branches:
      - main
      - next
      - renovate/**

  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

jobs:
  # verify against ranges defined as supported in engines.node
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 20.8.1
          - 20
          - 21
          - 18

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn audit signatures
      - run: yarn test

  # verify against the node version defined for development in the .nvmrc
  test_dev:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install
      - run: yarn audit signatures
      - run: yarn test

  # separate job to set as required in branch protection,
  # as the build names above change each time Node versions change
  test:
    runs-on: ubuntu-latest
    needs:
      - test_dev
      - test_matrix
    if: ${{ !cancelled() }}
    steps:
      - name: All matrix versions passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some matrix version failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1